/*
SendAuth API

Testing ApprovalGroupsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sendauth/api-clients/api"
)

func Test_api_ApprovalGroupsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ApprovalGroupsAPIService AddUserToAuthGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var userID string

		httpRes, err := apiClient.ApprovalGroupsAPI.AddUserToAuthGroup(context.Background(), id, userID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApprovalGroupsAPIService CreateAuthGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ApprovalGroupsAPI.CreateAuthGroup(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApprovalGroupsAPIService DeleteAuthGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.ApprovalGroupsAPI.DeleteAuthGroup(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApprovalGroupsAPIService GetAuthGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ApprovalGroupsAPI.GetAuthGroup(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApprovalGroupsAPIService ListAuthGroups", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ApprovalGroupsAPI.ListAuthGroups(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApprovalGroupsAPIService RemoveUserFromAuthGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var userID string

		httpRes, err := apiClient.ApprovalGroupsAPI.RemoveUserFromAuthGroup(context.Background(), id, userID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApprovalGroupsAPIService SetAuthGroupTags", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.ApprovalGroupsAPI.SetAuthGroupTags(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ApprovalGroupsAPIService UpdateAuthGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.ApprovalGroupsAPI.UpdateAuthGroup(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
