/*
SendAuth API

Testing TransactionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sendauth/api-clients/api"
)

func Test_api_TransactionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TransactionsAPIService CancelTransaction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var txID string

		httpRes, err := apiClient.TransactionsAPI.CancelTransaction(context.Background(), txID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionsAPIService CheckTransactionStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var txID string

		resp, httpRes, err := apiClient.TransactionsAPI.CheckTransactionStatus(context.Background(), txID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionsAPIService GetTransactionHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var txID string

		resp, httpRes, err := apiClient.TransactionsAPI.GetTransactionHistory(context.Background(), txID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionsAPIService ListTransactions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TransactionsAPI.ListTransactions(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionsAPIService SetTransactionTags", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var txID string

		httpRes, err := apiClient.TransactionsAPI.SetTransactionTags(context.Background(), txID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
