/*
SendAuth API

Testing UsersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sendauth/api-clients/api"
)

func Test_api_UsersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UsersAPIService AuthenticateUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userID string

		resp, httpRes, err := apiClient.UsersAPI.AuthenticateUser(context.Background(), userID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService CreateUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UsersAPI.CreateUser(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService DeleteUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userID string

		httpRes, err := apiClient.UsersAPI.DeleteUser(context.Background(), userID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService DestroyUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userID string

		httpRes, err := apiClient.UsersAPI.DestroyUser(context.Background(), userID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService GetUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userID string

		resp, httpRes, err := apiClient.UsersAPI.GetUser(context.Background(), userID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService GetUserAudits", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userID string

		resp, httpRes, err := apiClient.UsersAPI.GetUserAudits(context.Background(), userID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService GetUserTransactions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userID string

		resp, httpRes, err := apiClient.UsersAPI.GetUserTransactions(context.Background(), userID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService ListDeletedUsers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UsersAPI.ListDeletedUsers(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService ListUsers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.UsersAPI.ListUsers(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService RegisterUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userID string

		resp, httpRes, err := apiClient.UsersAPI.RegisterUser(context.Background(), userID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService RemoveUserPasskey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userID string

		httpRes, err := apiClient.UsersAPI.RemoveUserPasskey(context.Background(), userID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService RestoreUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userID string

		httpRes, err := apiClient.UsersAPI.RestoreUser(context.Background(), userID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService SetUserTags", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userID string

		httpRes, err := apiClient.UsersAPI.SetUserTags(context.Background(), userID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UsersAPIService UpdateUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userID string

		resp, httpRes, err := apiClient.UsersAPI.UpdateUser(context.Background(), userID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
