/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PaginatedTransactions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedTransactions{}

// PaginatedTransactions struct for PaginatedTransactions
type PaginatedTransactions struct {
	Rows []Transaction `json:"rows,omitempty"`
	// Total number of items
	Total *int64 `json:"total,omitempty"`
}

// NewPaginatedTransactions instantiates a new PaginatedTransactions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedTransactions() *PaginatedTransactions {
	this := PaginatedTransactions{}
	return &this
}

// NewPaginatedTransactionsWithDefaults instantiates a new PaginatedTransactions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedTransactionsWithDefaults() *PaginatedTransactions {
	this := PaginatedTransactions{}
	return &this
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *PaginatedTransactions) GetRows() []Transaction {
	if o == nil || IsNil(o.Rows) {
		var ret []Transaction
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedTransactions) GetRowsOk() ([]Transaction, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *PaginatedTransactions) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given []Transaction and assigns it to the Rows field.
func (o *PaginatedTransactions) SetRows(v []Transaction) {
	o.Rows = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PaginatedTransactions) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedTransactions) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PaginatedTransactions) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *PaginatedTransactions) SetTotal(v int64) {
	o.Total = &v
}

func (o PaginatedTransactions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedTransactions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullablePaginatedTransactions struct {
	value *PaginatedTransactions
	isSet bool
}

func (v NullablePaginatedTransactions) Get() *PaginatedTransactions {
	return v.value
}

func (v *NullablePaginatedTransactions) Set(val *PaginatedTransactions) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedTransactions) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedTransactions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedTransactions(val *PaginatedTransactions) *NullablePaginatedTransactions {
	return &NullablePaginatedTransactions{value: val, isSet: true}
}

func (v NullablePaginatedTransactions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedTransactions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


