/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the User type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &User{}

// User struct for User
type User struct {
	// Unique user identifier
	Id *string `json:"id,omitempty"`
	// User role
	Role *string `json:"role,omitempty"`
	// Display username
	Username *string `json:"username,omitempty"`
	// User first name
	FirstName string `json:"firstName"`
	// User last name
	LastName string `json:"lastName"`
	// User email address
	Email *string `json:"email,omitempty"`
	// User phone number
	Phone *string `json:"phone,omitempty"`
	Company *Company `json:"company,omitempty"`
	// User direct permissions
	Permissions []string `json:"permissions,omitempty"`
	// Permissions from groups
	GroupPermissions []string `json:"groupPermissions,omitempty"`
	// Permission group IDs
	PermissionGroups []string `json:"permissionGroups,omitempty"`
	// User messaging preference
	MessagingPreference *string `json:"messagingPreference,omitempty"`
	// Whether user has passkeys configured
	HasPasskeys *bool `json:"hasPasskeys,omitempty"`
	// User creation timestamp
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Last authentication timestamp
	LastAuthenticated *time.Time `json:"lastAuthenticated,omitempty"`
}

type _User User

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser(firstName string, lastName string) *User {
	this := User{}
	this.FirstName = firstName
	this.LastName = lastName
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *User) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *User) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *User) SetId(v string) {
	o.Id = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *User) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *User) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *User) SetRole(v string) {
	o.Role = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *User) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *User) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *User) SetUsername(v string) {
	o.Username = &v
}

// GetFirstName returns the FirstName field value
func (o *User) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *User) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *User) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *User) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *User) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *User) SetLastName(v string) {
	o.LastName = v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *User) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *User) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *User) SetEmail(v string) {
	o.Email = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *User) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *User) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *User) SetPhone(v string) {
	o.Phone = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *User) GetCompany() Company {
	if o == nil || IsNil(o.Company) {
		var ret Company
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetCompanyOk() (*Company, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *User) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given Company and assigns it to the Company field.
func (o *User) SetCompany(v Company) {
	o.Company = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *User) GetPermissions() []string {
	if o == nil || IsNil(o.Permissions) {
		var ret []string
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPermissionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *User) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *User) SetPermissions(v []string) {
	o.Permissions = v
}

// GetGroupPermissions returns the GroupPermissions field value if set, zero value otherwise.
func (o *User) GetGroupPermissions() []string {
	if o == nil || IsNil(o.GroupPermissions) {
		var ret []string
		return ret
	}
	return o.GroupPermissions
}

// GetGroupPermissionsOk returns a tuple with the GroupPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetGroupPermissionsOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupPermissions) {
		return nil, false
	}
	return o.GroupPermissions, true
}

// HasGroupPermissions returns a boolean if a field has been set.
func (o *User) HasGroupPermissions() bool {
	if o != nil && !IsNil(o.GroupPermissions) {
		return true
	}

	return false
}

// SetGroupPermissions gets a reference to the given []string and assigns it to the GroupPermissions field.
func (o *User) SetGroupPermissions(v []string) {
	o.GroupPermissions = v
}

// GetPermissionGroups returns the PermissionGroups field value if set, zero value otherwise.
func (o *User) GetPermissionGroups() []string {
	if o == nil || IsNil(o.PermissionGroups) {
		var ret []string
		return ret
	}
	return o.PermissionGroups
}

// GetPermissionGroupsOk returns a tuple with the PermissionGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPermissionGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.PermissionGroups) {
		return nil, false
	}
	return o.PermissionGroups, true
}

// HasPermissionGroups returns a boolean if a field has been set.
func (o *User) HasPermissionGroups() bool {
	if o != nil && !IsNil(o.PermissionGroups) {
		return true
	}

	return false
}

// SetPermissionGroups gets a reference to the given []string and assigns it to the PermissionGroups field.
func (o *User) SetPermissionGroups(v []string) {
	o.PermissionGroups = v
}

// GetMessagingPreference returns the MessagingPreference field value if set, zero value otherwise.
func (o *User) GetMessagingPreference() string {
	if o == nil || IsNil(o.MessagingPreference) {
		var ret string
		return ret
	}
	return *o.MessagingPreference
}

// GetMessagingPreferenceOk returns a tuple with the MessagingPreference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetMessagingPreferenceOk() (*string, bool) {
	if o == nil || IsNil(o.MessagingPreference) {
		return nil, false
	}
	return o.MessagingPreference, true
}

// HasMessagingPreference returns a boolean if a field has been set.
func (o *User) HasMessagingPreference() bool {
	if o != nil && !IsNil(o.MessagingPreference) {
		return true
	}

	return false
}

// SetMessagingPreference gets a reference to the given string and assigns it to the MessagingPreference field.
func (o *User) SetMessagingPreference(v string) {
	o.MessagingPreference = &v
}

// GetHasPasskeys returns the HasPasskeys field value if set, zero value otherwise.
func (o *User) GetHasPasskeys() bool {
	if o == nil || IsNil(o.HasPasskeys) {
		var ret bool
		return ret
	}
	return *o.HasPasskeys
}

// GetHasPasskeysOk returns a tuple with the HasPasskeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetHasPasskeysOk() (*bool, bool) {
	if o == nil || IsNil(o.HasPasskeys) {
		return nil, false
	}
	return o.HasPasskeys, true
}

// HasHasPasskeys returns a boolean if a field has been set.
func (o *User) HasHasPasskeys() bool {
	if o != nil && !IsNil(o.HasPasskeys) {
		return true
	}

	return false
}

// SetHasPasskeys gets a reference to the given bool and assigns it to the HasPasskeys field.
func (o *User) SetHasPasskeys(v bool) {
	o.HasPasskeys = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *User) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *User) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *User) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetLastAuthenticated returns the LastAuthenticated field value if set, zero value otherwise.
func (o *User) GetLastAuthenticated() time.Time {
	if o == nil || IsNil(o.LastAuthenticated) {
		var ret time.Time
		return ret
	}
	return *o.LastAuthenticated
}

// GetLastAuthenticatedOk returns a tuple with the LastAuthenticated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastAuthenticatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastAuthenticated) {
		return nil, false
	}
	return o.LastAuthenticated, true
}

// HasLastAuthenticated returns a boolean if a field has been set.
func (o *User) HasLastAuthenticated() bool {
	if o != nil && !IsNil(o.LastAuthenticated) {
		return true
	}

	return false
}

// SetLastAuthenticated gets a reference to the given time.Time and assigns it to the LastAuthenticated field.
func (o *User) SetLastAuthenticated(v time.Time) {
	o.LastAuthenticated = &v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o User) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	toSerialize["firstName"] = o.FirstName
	toSerialize["lastName"] = o.LastName
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if !IsNil(o.GroupPermissions) {
		toSerialize["groupPermissions"] = o.GroupPermissions
	}
	if !IsNil(o.PermissionGroups) {
		toSerialize["permissionGroups"] = o.PermissionGroups
	}
	if !IsNil(o.MessagingPreference) {
		toSerialize["messagingPreference"] = o.MessagingPreference
	}
	if !IsNil(o.HasPasskeys) {
		toSerialize["hasPasskeys"] = o.HasPasskeys
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.LastAuthenticated) {
		toSerialize["lastAuthenticated"] = o.LastAuthenticated
	}
	return toSerialize, nil
}

func (o *User) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"firstName",
		"lastName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUser := _User{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUser)

	if err != nil {
		return err
	}

	*o = User(varUser)

	return err
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


