/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
)

// checks if the OpenID type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenID{}

// OpenID struct for OpenID
type OpenID struct {
	// OpenID Connect issuer URL
	Issuer *string `json:"issuer,omitempty"`
	// OpenID Connect client ID
	ClientID *string `json:"clientID,omitempty"`
	// OpenID Connect client secret
	ClientSecret *string `json:"clientSecret,omitempty"`
}

// NewOpenID instantiates a new OpenID object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenID() *OpenID {
	this := OpenID{}
	return &this
}

// NewOpenIDWithDefaults instantiates a new OpenID object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenIDWithDefaults() *OpenID {
	this := OpenID{}
	return &this
}

// GetIssuer returns the Issuer field value if set, zero value otherwise.
func (o *OpenID) GetIssuer() string {
	if o == nil || IsNil(o.Issuer) {
		var ret string
		return ret
	}
	return *o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenID) GetIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.Issuer) {
		return nil, false
	}
	return o.Issuer, true
}

// HasIssuer returns a boolean if a field has been set.
func (o *OpenID) HasIssuer() bool {
	if o != nil && !IsNil(o.Issuer) {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given string and assigns it to the Issuer field.
func (o *OpenID) SetIssuer(v string) {
	o.Issuer = &v
}

// GetClientID returns the ClientID field value if set, zero value otherwise.
func (o *OpenID) GetClientID() string {
	if o == nil || IsNil(o.ClientID) {
		var ret string
		return ret
	}
	return *o.ClientID
}

// GetClientIDOk returns a tuple with the ClientID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenID) GetClientIDOk() (*string, bool) {
	if o == nil || IsNil(o.ClientID) {
		return nil, false
	}
	return o.ClientID, true
}

// HasClientID returns a boolean if a field has been set.
func (o *OpenID) HasClientID() bool {
	if o != nil && !IsNil(o.ClientID) {
		return true
	}

	return false
}

// SetClientID gets a reference to the given string and assigns it to the ClientID field.
func (o *OpenID) SetClientID(v string) {
	o.ClientID = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *OpenID) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenID) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *OpenID) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *OpenID) SetClientSecret(v string) {
	o.ClientSecret = &v
}

func (o OpenID) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenID) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Issuer) {
		toSerialize["issuer"] = o.Issuer
	}
	if !IsNil(o.ClientID) {
		toSerialize["clientID"] = o.ClientID
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	return toSerialize, nil
}

type NullableOpenID struct {
	value *OpenID
	isSet bool
}

func (v NullableOpenID) Get() *OpenID {
	return v.value
}

func (v *NullableOpenID) Set(val *OpenID) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenID) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenID) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenID(val *OpenID) *NullableOpenID {
	return &NullableOpenID{value: val, isSet: true}
}

func (v NullableOpenID) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenID) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


