/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
)

// checks if the PermissionGroupsReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionGroupsReply{}

// PermissionGroupsReply struct for PermissionGroupsReply
type PermissionGroupsReply struct {
	Groups []PermissionGroup `json:"groups,omitempty"`
}

// NewPermissionGroupsReply instantiates a new PermissionGroupsReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionGroupsReply() *PermissionGroupsReply {
	this := PermissionGroupsReply{}
	return &this
}

// NewPermissionGroupsReplyWithDefaults instantiates a new PermissionGroupsReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionGroupsReplyWithDefaults() *PermissionGroupsReply {
	this := PermissionGroupsReply{}
	return &this
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *PermissionGroupsReply) GetGroups() []PermissionGroup {
	if o == nil || IsNil(o.Groups) {
		var ret []PermissionGroup
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionGroupsReply) GetGroupsOk() ([]PermissionGroup, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *PermissionGroupsReply) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []PermissionGroup and assigns it to the Groups field.
func (o *PermissionGroupsReply) SetGroups(v []PermissionGroup) {
	o.Groups = v
}

func (o PermissionGroupsReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionGroupsReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	return toSerialize, nil
}

type NullablePermissionGroupsReply struct {
	value *PermissionGroupsReply
	isSet bool
}

func (v NullablePermissionGroupsReply) Get() *PermissionGroupsReply {
	return v.value
}

func (v *NullablePermissionGroupsReply) Set(val *PermissionGroupsReply) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionGroupsReply) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionGroupsReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionGroupsReply(val *PermissionGroupsReply) *NullablePermissionGroupsReply {
	return &NullablePermissionGroupsReply{value: val, isSet: true}
}

func (v NullablePermissionGroupsReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionGroupsReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


