/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
)

// checks if the WebhookEvents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEvents{}

// WebhookEvents struct for WebhookEvents
type WebhookEvents struct {
	// When true, transaction verifications will invoke the webhook
	Verify *bool `json:"verify,omitempty"`
	// When true, transaction denials will invoke the webhook
	Deny *bool `json:"deny,omitempty"`
}

// NewWebhookEvents instantiates a new WebhookEvents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEvents() *WebhookEvents {
	this := WebhookEvents{}
	return &this
}

// NewWebhookEventsWithDefaults instantiates a new WebhookEvents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEventsWithDefaults() *WebhookEvents {
	this := WebhookEvents{}
	return &this
}

// GetVerify returns the Verify field value if set, zero value otherwise.
func (o *WebhookEvents) GetVerify() bool {
	if o == nil || IsNil(o.Verify) {
		var ret bool
		return ret
	}
	return *o.Verify
}

// GetVerifyOk returns a tuple with the Verify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEvents) GetVerifyOk() (*bool, bool) {
	if o == nil || IsNil(o.Verify) {
		return nil, false
	}
	return o.Verify, true
}

// HasVerify returns a boolean if a field has been set.
func (o *WebhookEvents) HasVerify() bool {
	if o != nil && !IsNil(o.Verify) {
		return true
	}

	return false
}

// SetVerify gets a reference to the given bool and assigns it to the Verify field.
func (o *WebhookEvents) SetVerify(v bool) {
	o.Verify = &v
}

// GetDeny returns the Deny field value if set, zero value otherwise.
func (o *WebhookEvents) GetDeny() bool {
	if o == nil || IsNil(o.Deny) {
		var ret bool
		return ret
	}
	return *o.Deny
}

// GetDenyOk returns a tuple with the Deny field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEvents) GetDenyOk() (*bool, bool) {
	if o == nil || IsNil(o.Deny) {
		return nil, false
	}
	return o.Deny, true
}

// HasDeny returns a boolean if a field has been set.
func (o *WebhookEvents) HasDeny() bool {
	if o != nil && !IsNil(o.Deny) {
		return true
	}

	return false
}

// SetDeny gets a reference to the given bool and assigns it to the Deny field.
func (o *WebhookEvents) SetDeny(v bool) {
	o.Deny = &v
}

func (o WebhookEvents) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEvents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Verify) {
		toSerialize["verify"] = o.Verify
	}
	if !IsNil(o.Deny) {
		toSerialize["deny"] = o.Deny
	}
	return toSerialize, nil
}

type NullableWebhookEvents struct {
	value *WebhookEvents
	isSet bool
}

func (v NullableWebhookEvents) Get() *WebhookEvents {
	return v.value
}

func (v *NullableWebhookEvents) Set(val *WebhookEvents) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEvents) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEvents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEvents(val *WebhookEvents) *NullableWebhookEvents {
	return &NullableWebhookEvents{value: val, isSet: true}
}

func (v NullableWebhookEvents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEvents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


