/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
)

// checks if the TX type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TX{}

// TX struct for TX
type TX struct {
	// Transaction ID
	Tx *string `json:"tx,omitempty"`
}

// NewTX instantiates a new TX object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTX() *TX {
	this := TX{}
	return &this
}

// NewTXWithDefaults instantiates a new TX object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTXWithDefaults() *TX {
	this := TX{}
	return &this
}

// GetTx returns the Tx field value if set, zero value otherwise.
func (o *TX) GetTx() string {
	if o == nil || IsNil(o.Tx) {
		var ret string
		return ret
	}
	return *o.Tx
}

// GetTxOk returns a tuple with the Tx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TX) GetTxOk() (*string, bool) {
	if o == nil || IsNil(o.Tx) {
		return nil, false
	}
	return o.Tx, true
}

// HasTx returns a boolean if a field has been set.
func (o *TX) HasTx() bool {
	if o != nil && !IsNil(o.Tx) {
		return true
	}

	return false
}

// SetTx gets a reference to the given string and assigns it to the Tx field.
func (o *TX) SetTx(v string) {
	o.Tx = &v
}

func (o TX) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TX) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tx) {
		toSerialize["tx"] = o.Tx
	}
	return toSerialize, nil
}

type NullableTX struct {
	value *TX
	isSet bool
}

func (v NullableTX) Get() *TX {
	return v.value
}

func (v *NullableTX) Set(val *TX) {
	v.value = val
	v.isSet = true
}

func (v NullableTX) IsSet() bool {
	return v.isSet
}

func (v *NullableTX) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTX(val *TX) *NullableTX {
	return &NullableTX{value: val, isSet: true}
}

func (v NullableTX) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTX) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


