/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PaginatedAudits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedAudits{}

// PaginatedAudits struct for PaginatedAudits
type PaginatedAudits struct {
	Rows []Audit `json:"rows,omitempty"`
	// Total number of items
	Total *int64 `json:"total,omitempty"`
}

// NewPaginatedAudits instantiates a new PaginatedAudits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedAudits() *PaginatedAudits {
	this := PaginatedAudits{}
	return &this
}

// NewPaginatedAuditsWithDefaults instantiates a new PaginatedAudits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedAuditsWithDefaults() *PaginatedAudits {
	this := PaginatedAudits{}
	return &this
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *PaginatedAudits) GetRows() []Audit {
	if o == nil || IsNil(o.Rows) {
		var ret []Audit
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedAudits) GetRowsOk() ([]Audit, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *PaginatedAudits) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given []Audit and assigns it to the Rows field.
func (o *PaginatedAudits) SetRows(v []Audit) {
	o.Rows = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PaginatedAudits) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedAudits) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PaginatedAudits) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *PaginatedAudits) SetTotal(v int64) {
	o.Total = &v
}

func (o PaginatedAudits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedAudits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullablePaginatedAudits struct {
	value *PaginatedAudits
	isSet bool
}

func (v NullablePaginatedAudits) Get() *PaginatedAudits {
	return v.value
}

func (v *NullablePaginatedAudits) Set(val *PaginatedAudits) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedAudits) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedAudits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedAudits(val *PaginatedAudits) *NullablePaginatedAudits {
	return &NullablePaginatedAudits{value: val, isSet: true}
}

func (v NullablePaginatedAudits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedAudits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


