/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
)

// checks if the TagListReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagListReply{}

// TagListReply struct for TagListReply
type TagListReply struct {
	Tags []Tag `json:"tags,omitempty"`
}

// NewTagListReply instantiates a new TagListReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagListReply() *TagListReply {
	this := TagListReply{}
	return &this
}

// NewTagListReplyWithDefaults instantiates a new TagListReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagListReplyWithDefaults() *TagListReply {
	this := TagListReply{}
	return &this
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *TagListReply) GetTags() []Tag {
	if o == nil || IsNil(o.Tags) {
		var ret []Tag
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagListReply) GetTagsOk() ([]Tag, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *TagListReply) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []Tag and assigns it to the Tags field.
func (o *TagListReply) SetTags(v []Tag) {
	o.Tags = v
}

func (o TagListReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagListReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableTagListReply struct {
	value *TagListReply
	isSet bool
}

func (v NullableTagListReply) Get() *TagListReply {
	return v.value
}

func (v *NullableTagListReply) Set(val *TagListReply) {
	v.value = val
	v.isSet = true
}

func (v NullableTagListReply) IsSet() bool {
	return v.isSet
}

func (v *NullableTagListReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagListReply(val *TagListReply) *NullableTagListReply {
	return &NullableTagListReply{value: val, isSet: true}
}

func (v NullableTagListReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagListReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


