/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
)

// checks if the PermissionsReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionsReply{}

// PermissionsReply struct for PermissionsReply
type PermissionsReply struct {
	Permissions []Permission `json:"permissions,omitempty"`
}

// NewPermissionsReply instantiates a new PermissionsReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionsReply() *PermissionsReply {
	this := PermissionsReply{}
	return &this
}

// NewPermissionsReplyWithDefaults instantiates a new PermissionsReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionsReplyWithDefaults() *PermissionsReply {
	this := PermissionsReply{}
	return &this
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *PermissionsReply) GetPermissions() []Permission {
	if o == nil || IsNil(o.Permissions) {
		var ret []Permission
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionsReply) GetPermissionsOk() ([]Permission, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *PermissionsReply) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []Permission and assigns it to the Permissions field.
func (o *PermissionsReply) SetPermissions(v []Permission) {
	o.Permissions = v
}

func (o PermissionsReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionsReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

type NullablePermissionsReply struct {
	value *PermissionsReply
	isSet bool
}

func (v NullablePermissionsReply) Get() *PermissionsReply {
	return v.value
}

func (v *NullablePermissionsReply) Set(val *PermissionsReply) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionsReply) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionsReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionsReply(val *PermissionsReply) *NullablePermissionsReply {
	return &NullablePermissionsReply{value: val, isSet: true}
}

func (v NullablePermissionsReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionsReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


