/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UpdateTagValueRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTagValueRequest{}

// UpdateTagValueRequest struct for UpdateTagValueRequest
type UpdateTagValueRequest struct {
	// New value for the tag
	Value *string `json:"value,omitempty"`
}

// NewUpdateTagValueRequest instantiates a new UpdateTagValueRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTagValueRequest() *UpdateTagValueRequest {
	this := UpdateTagValueRequest{}
	return &this
}

// NewUpdateTagValueRequestWithDefaults instantiates a new UpdateTagValueRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTagValueRequestWithDefaults() *UpdateTagValueRequest {
	this := UpdateTagValueRequest{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *UpdateTagValueRequest) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTagValueRequest) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *UpdateTagValueRequest) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *UpdateTagValueRequest) SetValue(v string) {
	o.Value = &v
}

func (o UpdateTagValueRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTagValueRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableUpdateTagValueRequest struct {
	value *UpdateTagValueRequest
	isSet bool
}

func (v NullableUpdateTagValueRequest) Get() *UpdateTagValueRequest {
	return v.value
}

func (v *NullableUpdateTagValueRequest) Set(val *UpdateTagValueRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTagValueRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTagValueRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTagValueRequest(val *UpdateTagValueRequest) *NullableUpdateTagValueRequest {
	return &NullableUpdateTagValueRequest{value: val, isSet: true}
}

func (v NullableUpdateTagValueRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTagValueRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


