/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// AuthorizeReply - struct for AuthorizeReply
type AuthorizeReply struct {
	AuthorizeReplyOneOf *AuthorizeReplyOneOf
	AuthorizeReplyOneOf1 *AuthorizeReplyOneOf1
}

// AuthorizeReplyOneOfAsAuthorizeReply is a convenience function that returns AuthorizeReplyOneOf wrapped in AuthorizeReply
func AuthorizeReplyOneOfAsAuthorizeReply(v *AuthorizeReplyOneOf) AuthorizeReply {
	return AuthorizeReply{
		AuthorizeReplyOneOf: v,
	}
}

// AuthorizeReplyOneOf1AsAuthorizeReply is a convenience function that returns AuthorizeReplyOneOf1 wrapped in AuthorizeReply
func AuthorizeReplyOneOf1AsAuthorizeReply(v *AuthorizeReplyOneOf1) AuthorizeReply {
	return AuthorizeReply{
		AuthorizeReplyOneOf1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *AuthorizeReply) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AuthorizeReplyOneOf
	err = newStrictDecoder(data).Decode(&dst.AuthorizeReplyOneOf)
	if err == nil {
		jsonAuthorizeReplyOneOf, _ := json.Marshal(dst.AuthorizeReplyOneOf)
		if string(jsonAuthorizeReplyOneOf) == "{}" { // empty struct
			dst.AuthorizeReplyOneOf = nil
		} else {
			if err = validator.Validate(dst.AuthorizeReplyOneOf); err != nil {
				dst.AuthorizeReplyOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthorizeReplyOneOf = nil
	}

	// try to unmarshal data into AuthorizeReplyOneOf1
	err = newStrictDecoder(data).Decode(&dst.AuthorizeReplyOneOf1)
	if err == nil {
		jsonAuthorizeReplyOneOf1, _ := json.Marshal(dst.AuthorizeReplyOneOf1)
		if string(jsonAuthorizeReplyOneOf1) == "{}" { // empty struct
			dst.AuthorizeReplyOneOf1 = nil
		} else {
			if err = validator.Validate(dst.AuthorizeReplyOneOf1); err != nil {
				dst.AuthorizeReplyOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthorizeReplyOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AuthorizeReplyOneOf = nil
		dst.AuthorizeReplyOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(AuthorizeReply)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(AuthorizeReply)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AuthorizeReply) MarshalJSON() ([]byte, error) {
	if src.AuthorizeReplyOneOf != nil {
		return json.Marshal(&src.AuthorizeReplyOneOf)
	}

	if src.AuthorizeReplyOneOf1 != nil {
		return json.Marshal(&src.AuthorizeReplyOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AuthorizeReply) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AuthorizeReplyOneOf != nil {
		return obj.AuthorizeReplyOneOf
	}

	if obj.AuthorizeReplyOneOf1 != nil {
		return obj.AuthorizeReplyOneOf1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj AuthorizeReply) GetActualInstanceValue() (interface{}) {
	if obj.AuthorizeReplyOneOf != nil {
		return *obj.AuthorizeReplyOneOf
	}

	if obj.AuthorizeReplyOneOf1 != nil {
		return *obj.AuthorizeReplyOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableAuthorizeReply struct {
	value *AuthorizeReply
	isSet bool
}

func (v NullableAuthorizeReply) Get() *AuthorizeReply {
	return v.value
}

func (v *NullableAuthorizeReply) Set(val *AuthorizeReply) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizeReply) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizeReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizeReply(val *AuthorizeReply) *NullableAuthorizeReply {
	return &NullableAuthorizeReply{value: val, isSet: true}
}

func (v NullableAuthorizeReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizeReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


