/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
)

// checks if the CheckTransactionStatus200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckTransactionStatus200Response{}

// CheckTransactionStatus200Response struct for CheckTransactionStatus200Response
type CheckTransactionStatus200Response struct {
	State *string `json:"state,omitempty"`
}

// NewCheckTransactionStatus200Response instantiates a new CheckTransactionStatus200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckTransactionStatus200Response() *CheckTransactionStatus200Response {
	this := CheckTransactionStatus200Response{}
	return &this
}

// NewCheckTransactionStatus200ResponseWithDefaults instantiates a new CheckTransactionStatus200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckTransactionStatus200ResponseWithDefaults() *CheckTransactionStatus200Response {
	this := CheckTransactionStatus200Response{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *CheckTransactionStatus200Response) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckTransactionStatus200Response) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *CheckTransactionStatus200Response) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *CheckTransactionStatus200Response) SetState(v string) {
	o.State = &v
}

func (o CheckTransactionStatus200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckTransactionStatus200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableCheckTransactionStatus200Response struct {
	value *CheckTransactionStatus200Response
	isSet bool
}

func (v NullableCheckTransactionStatus200Response) Get() *CheckTransactionStatus200Response {
	return v.value
}

func (v *NullableCheckTransactionStatus200Response) Set(val *CheckTransactionStatus200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckTransactionStatus200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckTransactionStatus200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckTransactionStatus200Response(val *CheckTransactionStatus200Response) *NullableCheckTransactionStatus200Response {
	return &NullableCheckTransactionStatus200Response{value: val, isSet: true}
}

func (v NullableCheckTransactionStatus200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckTransactionStatus200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


