/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PaginatedUsers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedUsers{}

// PaginatedUsers struct for PaginatedUsers
type PaginatedUsers struct {
	Rows []User `json:"rows,omitempty"`
	// Total number of items
	Total *int64 `json:"total,omitempty"`
}

// NewPaginatedUsers instantiates a new PaginatedUsers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedUsers() *PaginatedUsers {
	this := PaginatedUsers{}
	return &this
}

// NewPaginatedUsersWithDefaults instantiates a new PaginatedUsers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedUsersWithDefaults() *PaginatedUsers {
	this := PaginatedUsers{}
	return &this
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *PaginatedUsers) GetRows() []User {
	if o == nil || IsNil(o.Rows) {
		var ret []User
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedUsers) GetRowsOk() ([]User, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *PaginatedUsers) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given []User and assigns it to the Rows field.
func (o *PaginatedUsers) SetRows(v []User) {
	o.Rows = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PaginatedUsers) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedUsers) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PaginatedUsers) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *PaginatedUsers) SetTotal(v int64) {
	o.Total = &v
}

func (o PaginatedUsers) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedUsers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullablePaginatedUsers struct {
	value *PaginatedUsers
	isSet bool
}

func (v NullablePaginatedUsers) Get() *PaginatedUsers {
	return v.value
}

func (v *NullablePaginatedUsers) Set(val *PaginatedUsers) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedUsers) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedUsers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedUsers(val *PaginatedUsers) *NullablePaginatedUsers {
	return &NullablePaginatedUsers{value: val, isSet: true}
}

func (v NullablePaginatedUsers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedUsers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


