/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the WebTX type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebTX{}

// WebTX struct for WebTX
type WebTX struct {
	// Transaction message
	Message *string `json:"message,omitempty"`
	// ConnectWise reference
	Connectwise *string `json:"connectwise,omitempty"`
}

// NewWebTX instantiates a new WebTX object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebTX() *WebTX {
	this := WebTX{}
	return &this
}

// NewWebTXWithDefaults instantiates a new WebTX object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebTXWithDefaults() *WebTX {
	this := WebTX{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *WebTX) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebTX) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *WebTX) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *WebTX) SetMessage(v string) {
	o.Message = &v
}

// GetConnectwise returns the Connectwise field value if set, zero value otherwise.
func (o *WebTX) GetConnectwise() string {
	if o == nil || IsNil(o.Connectwise) {
		var ret string
		return ret
	}
	return *o.Connectwise
}

// GetConnectwiseOk returns a tuple with the Connectwise field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebTX) GetConnectwiseOk() (*string, bool) {
	if o == nil || IsNil(o.Connectwise) {
		return nil, false
	}
	return o.Connectwise, true
}

// HasConnectwise returns a boolean if a field has been set.
func (o *WebTX) HasConnectwise() bool {
	if o != nil && !IsNil(o.Connectwise) {
		return true
	}

	return false
}

// SetConnectwise gets a reference to the given string and assigns it to the Connectwise field.
func (o *WebTX) SetConnectwise(v string) {
	o.Connectwise = &v
}

func (o WebTX) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebTX) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Connectwise) {
		toSerialize["connectwise"] = o.Connectwise
	}
	return toSerialize, nil
}

type NullableWebTX struct {
	value *WebTX
	isSet bool
}

func (v NullableWebTX) Get() *WebTX {
	return v.value
}

func (v *NullableWebTX) Set(val *WebTX) {
	v.value = val
	v.isSet = true
}

func (v NullableWebTX) IsSet() bool {
	return v.isSet
}

func (v *NullableWebTX) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebTX(val *WebTX) *NullableWebTX {
	return &NullableWebTX{value: val, isSet: true}
}

func (v NullableWebTX) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebTX) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


