/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the Settings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Settings{}

// Settings struct for Settings
type Settings struct {
	// Organization subdomain
	Subdomain *string `json:"subdomain,omitempty"`
	// Organization name
	Name *string `json:"name,omitempty"`
	OpenID *OpenID `json:"openID,omitempty"`
	// SCIM API secret
	ScimSecret *string `json:"scimSecret,omitempty"`
	// Email notification template
	EmailTemplate *string `json:"emailTemplate,omitempty"`
	// SMS notification template
	SmsTemplate *string `json:"smsTemplate,omitempty"`
	ConnectWise *ConnectWise `json:"connectWise,omitempty"`
}

// NewSettings instantiates a new Settings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettings() *Settings {
	this := Settings{}
	return &this
}

// NewSettingsWithDefaults instantiates a new Settings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsWithDefaults() *Settings {
	this := Settings{}
	return &this
}

// GetSubdomain returns the Subdomain field value if set, zero value otherwise.
func (o *Settings) GetSubdomain() string {
	if o == nil || IsNil(o.Subdomain) {
		var ret string
		return ret
	}
	return *o.Subdomain
}

// GetSubdomainOk returns a tuple with the Subdomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetSubdomainOk() (*string, bool) {
	if o == nil || IsNil(o.Subdomain) {
		return nil, false
	}
	return o.Subdomain, true
}

// HasSubdomain returns a boolean if a field has been set.
func (o *Settings) HasSubdomain() bool {
	if o != nil && !IsNil(o.Subdomain) {
		return true
	}

	return false
}

// SetSubdomain gets a reference to the given string and assigns it to the Subdomain field.
func (o *Settings) SetSubdomain(v string) {
	o.Subdomain = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Settings) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Settings) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Settings) SetName(v string) {
	o.Name = &v
}

// GetOpenID returns the OpenID field value if set, zero value otherwise.
func (o *Settings) GetOpenID() OpenID {
	if o == nil || IsNil(o.OpenID) {
		var ret OpenID
		return ret
	}
	return *o.OpenID
}

// GetOpenIDOk returns a tuple with the OpenID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOpenIDOk() (*OpenID, bool) {
	if o == nil || IsNil(o.OpenID) {
		return nil, false
	}
	return o.OpenID, true
}

// HasOpenID returns a boolean if a field has been set.
func (o *Settings) HasOpenID() bool {
	if o != nil && !IsNil(o.OpenID) {
		return true
	}

	return false
}

// SetOpenID gets a reference to the given OpenID and assigns it to the OpenID field.
func (o *Settings) SetOpenID(v OpenID) {
	o.OpenID = &v
}

// GetScimSecret returns the ScimSecret field value if set, zero value otherwise.
func (o *Settings) GetScimSecret() string {
	if o == nil || IsNil(o.ScimSecret) {
		var ret string
		return ret
	}
	return *o.ScimSecret
}

// GetScimSecretOk returns a tuple with the ScimSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetScimSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ScimSecret) {
		return nil, false
	}
	return o.ScimSecret, true
}

// HasScimSecret returns a boolean if a field has been set.
func (o *Settings) HasScimSecret() bool {
	if o != nil && !IsNil(o.ScimSecret) {
		return true
	}

	return false
}

// SetScimSecret gets a reference to the given string and assigns it to the ScimSecret field.
func (o *Settings) SetScimSecret(v string) {
	o.ScimSecret = &v
}

// GetEmailTemplate returns the EmailTemplate field value if set, zero value otherwise.
func (o *Settings) GetEmailTemplate() string {
	if o == nil || IsNil(o.EmailTemplate) {
		var ret string
		return ret
	}
	return *o.EmailTemplate
}

// GetEmailTemplateOk returns a tuple with the EmailTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetEmailTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.EmailTemplate) {
		return nil, false
	}
	return o.EmailTemplate, true
}

// HasEmailTemplate returns a boolean if a field has been set.
func (o *Settings) HasEmailTemplate() bool {
	if o != nil && !IsNil(o.EmailTemplate) {
		return true
	}

	return false
}

// SetEmailTemplate gets a reference to the given string and assigns it to the EmailTemplate field.
func (o *Settings) SetEmailTemplate(v string) {
	o.EmailTemplate = &v
}

// GetSmsTemplate returns the SmsTemplate field value if set, zero value otherwise.
func (o *Settings) GetSmsTemplate() string {
	if o == nil || IsNil(o.SmsTemplate) {
		var ret string
		return ret
	}
	return *o.SmsTemplate
}

// GetSmsTemplateOk returns a tuple with the SmsTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetSmsTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.SmsTemplate) {
		return nil, false
	}
	return o.SmsTemplate, true
}

// HasSmsTemplate returns a boolean if a field has been set.
func (o *Settings) HasSmsTemplate() bool {
	if o != nil && !IsNil(o.SmsTemplate) {
		return true
	}

	return false
}

// SetSmsTemplate gets a reference to the given string and assigns it to the SmsTemplate field.
func (o *Settings) SetSmsTemplate(v string) {
	o.SmsTemplate = &v
}

// GetConnectWise returns the ConnectWise field value if set, zero value otherwise.
func (o *Settings) GetConnectWise() ConnectWise {
	if o == nil || IsNil(o.ConnectWise) {
		var ret ConnectWise
		return ret
	}
	return *o.ConnectWise
}

// GetConnectWiseOk returns a tuple with the ConnectWise field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetConnectWiseOk() (*ConnectWise, bool) {
	if o == nil || IsNil(o.ConnectWise) {
		return nil, false
	}
	return o.ConnectWise, true
}

// HasConnectWise returns a boolean if a field has been set.
func (o *Settings) HasConnectWise() bool {
	if o != nil && !IsNil(o.ConnectWise) {
		return true
	}

	return false
}

// SetConnectWise gets a reference to the given ConnectWise and assigns it to the ConnectWise field.
func (o *Settings) SetConnectWise(v ConnectWise) {
	o.ConnectWise = &v
}

func (o Settings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Settings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Subdomain) {
		toSerialize["subdomain"] = o.Subdomain
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OpenID) {
		toSerialize["openID"] = o.OpenID
	}
	if !IsNil(o.ScimSecret) {
		toSerialize["scimSecret"] = o.ScimSecret
	}
	if !IsNil(o.EmailTemplate) {
		toSerialize["emailTemplate"] = o.EmailTemplate
	}
	if !IsNil(o.SmsTemplate) {
		toSerialize["smsTemplate"] = o.SmsTemplate
	}
	if !IsNil(o.ConnectWise) {
		toSerialize["connectWise"] = o.ConnectWise
	}
	return toSerialize, nil
}

type NullableSettings struct {
	value *Settings
	isSet bool
}

func (v NullableSettings) Get() *Settings {
	return v.value
}

func (v *NullableSettings) Set(val *Settings) {
	v.value = val
	v.isSet = true
}

func (v NullableSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettings(val *Settings) *NullableSettings {
	return &NullableSettings{value: val, isSet: true}
}

func (v NullableSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


