/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ConnectWise type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectWise{}

// ConnectWise struct for ConnectWise
type ConnectWise struct {
	// Whether ConnectWise integration is enabled
	Enabled *bool `json:"enabled,omitempty"`
	// ConnectWise server URL
	ServerURL *string `json:"serverURL,omitempty"`
	// ConnectWise company ID
	CompanyID *string `json:"companyID,omitempty"`
	// ConnectWise public key
	PublicKey *string `json:"publicKey,omitempty"`
	// ConnectWise private key
	PrivateKey *string `json:"privateKey,omitempty"`
	// ConnectWise API version
	ApiVersion *string `json:"apiVersion,omitempty"`
}

// NewConnectWise instantiates a new ConnectWise object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectWise() *ConnectWise {
	this := ConnectWise{}
	return &this
}

// NewConnectWiseWithDefaults instantiates a new ConnectWise object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectWiseWithDefaults() *ConnectWise {
	this := ConnectWise{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ConnectWise) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectWise) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ConnectWise) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ConnectWise) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetServerURL returns the ServerURL field value if set, zero value otherwise.
func (o *ConnectWise) GetServerURL() string {
	if o == nil || IsNil(o.ServerURL) {
		var ret string
		return ret
	}
	return *o.ServerURL
}

// GetServerURLOk returns a tuple with the ServerURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectWise) GetServerURLOk() (*string, bool) {
	if o == nil || IsNil(o.ServerURL) {
		return nil, false
	}
	return o.ServerURL, true
}

// HasServerURL returns a boolean if a field has been set.
func (o *ConnectWise) HasServerURL() bool {
	if o != nil && !IsNil(o.ServerURL) {
		return true
	}

	return false
}

// SetServerURL gets a reference to the given string and assigns it to the ServerURL field.
func (o *ConnectWise) SetServerURL(v string) {
	o.ServerURL = &v
}

// GetCompanyID returns the CompanyID field value if set, zero value otherwise.
func (o *ConnectWise) GetCompanyID() string {
	if o == nil || IsNil(o.CompanyID) {
		var ret string
		return ret
	}
	return *o.CompanyID
}

// GetCompanyIDOk returns a tuple with the CompanyID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectWise) GetCompanyIDOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyID) {
		return nil, false
	}
	return o.CompanyID, true
}

// HasCompanyID returns a boolean if a field has been set.
func (o *ConnectWise) HasCompanyID() bool {
	if o != nil && !IsNil(o.CompanyID) {
		return true
	}

	return false
}

// SetCompanyID gets a reference to the given string and assigns it to the CompanyID field.
func (o *ConnectWise) SetCompanyID(v string) {
	o.CompanyID = &v
}

// GetPublicKey returns the PublicKey field value if set, zero value otherwise.
func (o *ConnectWise) GetPublicKey() string {
	if o == nil || IsNil(o.PublicKey) {
		var ret string
		return ret
	}
	return *o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectWise) GetPublicKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PublicKey) {
		return nil, false
	}
	return o.PublicKey, true
}

// HasPublicKey returns a boolean if a field has been set.
func (o *ConnectWise) HasPublicKey() bool {
	if o != nil && !IsNil(o.PublicKey) {
		return true
	}

	return false
}

// SetPublicKey gets a reference to the given string and assigns it to the PublicKey field.
func (o *ConnectWise) SetPublicKey(v string) {
	o.PublicKey = &v
}

// GetPrivateKey returns the PrivateKey field value if set, zero value otherwise.
func (o *ConnectWise) GetPrivateKey() string {
	if o == nil || IsNil(o.PrivateKey) {
		var ret string
		return ret
	}
	return *o.PrivateKey
}

// GetPrivateKeyOk returns a tuple with the PrivateKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectWise) GetPrivateKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateKey) {
		return nil, false
	}
	return o.PrivateKey, true
}

// HasPrivateKey returns a boolean if a field has been set.
func (o *ConnectWise) HasPrivateKey() bool {
	if o != nil && !IsNil(o.PrivateKey) {
		return true
	}

	return false
}

// SetPrivateKey gets a reference to the given string and assigns it to the PrivateKey field.
func (o *ConnectWise) SetPrivateKey(v string) {
	o.PrivateKey = &v
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *ConnectWise) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectWise) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *ConnectWise) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *ConnectWise) SetApiVersion(v string) {
	o.ApiVersion = &v
}

func (o ConnectWise) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectWise) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.ServerURL) {
		toSerialize["serverURL"] = o.ServerURL
	}
	if !IsNil(o.CompanyID) {
		toSerialize["companyID"] = o.CompanyID
	}
	if !IsNil(o.PublicKey) {
		toSerialize["publicKey"] = o.PublicKey
	}
	if !IsNil(o.PrivateKey) {
		toSerialize["privateKey"] = o.PrivateKey
	}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	return toSerialize, nil
}

type NullableConnectWise struct {
	value *ConnectWise
	isSet bool
}

func (v NullableConnectWise) Get() *ConnectWise {
	return v.value
}

func (v *NullableConnectWise) Set(val *ConnectWise) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectWise) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectWise) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectWise(val *ConnectWise) *NullableConnectWise {
	return &NullableConnectWise{value: val, isSet: true}
}

func (v NullableConnectWise) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectWise) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


