/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SetPermissionGroupPermissionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetPermissionGroupPermissionsRequest{}

// SetPermissionGroupPermissionsRequest struct for SetPermissionGroupPermissionsRequest
type SetPermissionGroupPermissionsRequest struct {
	Permissions []string `json:"permissions,omitempty"`
}

// NewSetPermissionGroupPermissionsRequest instantiates a new SetPermissionGroupPermissionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetPermissionGroupPermissionsRequest() *SetPermissionGroupPermissionsRequest {
	this := SetPermissionGroupPermissionsRequest{}
	return &this
}

// NewSetPermissionGroupPermissionsRequestWithDefaults instantiates a new SetPermissionGroupPermissionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetPermissionGroupPermissionsRequestWithDefaults() *SetPermissionGroupPermissionsRequest {
	this := SetPermissionGroupPermissionsRequest{}
	return &this
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *SetPermissionGroupPermissionsRequest) GetPermissions() []string {
	if o == nil || IsNil(o.Permissions) {
		var ret []string
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetPermissionGroupPermissionsRequest) GetPermissionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *SetPermissionGroupPermissionsRequest) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *SetPermissionGroupPermissionsRequest) SetPermissions(v []string) {
	o.Permissions = v
}

func (o SetPermissionGroupPermissionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetPermissionGroupPermissionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

type NullableSetPermissionGroupPermissionsRequest struct {
	value *SetPermissionGroupPermissionsRequest
	isSet bool
}

func (v NullableSetPermissionGroupPermissionsRequest) Get() *SetPermissionGroupPermissionsRequest {
	return v.value
}

func (v *NullableSetPermissionGroupPermissionsRequest) Set(val *SetPermissionGroupPermissionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetPermissionGroupPermissionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetPermissionGroupPermissionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetPermissionGroupPermissionsRequest(val *SetPermissionGroupPermissionsRequest) *NullableSetPermissionGroupPermissionsRequest {
	return &NullableSetPermissionGroupPermissionsRequest{value: val, isSet: true}
}

func (v NullableSetPermissionGroupPermissionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetPermissionGroupPermissionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


