/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthGroup{}

// AuthGroup struct for AuthGroup
type AuthGroup struct {
	// The unique identifier of the approval group
	Id *string `json:"id,omitempty"`
	// The name of the approval group
	Name string `json:"name"`
	// The threshold for the approval group
	Threshold string `json:"threshold"`
	Description *string `json:"description,omitempty"`
	Users []AuthGroupMember `json:"users,omitempty"`
}

type _AuthGroup AuthGroup

// NewAuthGroup instantiates a new AuthGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthGroup(name string, threshold string) *AuthGroup {
	this := AuthGroup{}
	this.Name = name
	this.Threshold = threshold
	return &this
}

// NewAuthGroupWithDefaults instantiates a new AuthGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthGroupWithDefaults() *AuthGroup {
	this := AuthGroup{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AuthGroup) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthGroup) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AuthGroup) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AuthGroup) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *AuthGroup) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AuthGroup) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AuthGroup) SetName(v string) {
	o.Name = v
}

// GetThreshold returns the Threshold field value
func (o *AuthGroup) GetThreshold() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value
// and a boolean to check if the value has been set.
func (o *AuthGroup) GetThresholdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threshold, true
}

// SetThreshold sets field value
func (o *AuthGroup) SetThreshold(v string) {
	o.Threshold = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AuthGroup) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthGroup) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AuthGroup) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AuthGroup) SetDescription(v string) {
	o.Description = &v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *AuthGroup) GetUsers() []AuthGroupMember {
	if o == nil || IsNil(o.Users) {
		var ret []AuthGroupMember
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthGroup) GetUsersOk() ([]AuthGroupMember, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *AuthGroup) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []AuthGroupMember and assigns it to the Users field.
func (o *AuthGroup) SetUsers(v []AuthGroupMember) {
	o.Users = v
}

func (o AuthGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	toSerialize["threshold"] = o.Threshold
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	return toSerialize, nil
}

func (o *AuthGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"threshold",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthGroup := _AuthGroup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthGroup)

	if err != nil {
		return err
	}

	*o = AuthGroup(varAuthGroup)

	return err
}

type NullableAuthGroup struct {
	value *AuthGroup
	isSet bool
}

func (v NullableAuthGroup) Get() *AuthGroup {
	return v.value
}

func (v *NullableAuthGroup) Set(val *AuthGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthGroup(val *AuthGroup) *NullableAuthGroup {
	return &NullableAuthGroup{value: val, isSet: true}
}

func (v NullableAuthGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


