/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RoutingRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoutingRule{}

// RoutingRule struct for RoutingRule
type RoutingRule struct {
	Id *string `json:"id,omitempty"`
	// Name of tag associated with the routing rule
	TagName string `json:"tagName"`
	// Tag value that must match for this rule to fire
	TagValue string `json:"tagValue"`
	Description *string `json:"description,omitempty"`
	// The type of target for the routing rule
	TargetType string `json:"targetType"`
	// The ID of the target (approval group or user)
	TargetId string `json:"targetId"`
	// The email of the target
	TargetEmail *string `json:"targetEmail,omitempty"`
	// The name of the target
	TargetName *string `json:"targetName,omitempty"`
}

type _RoutingRule RoutingRule

// NewRoutingRule instantiates a new RoutingRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutingRule(tagName string, tagValue string, targetType string, targetId string) *RoutingRule {
	this := RoutingRule{}
	this.TagName = tagName
	this.TagValue = tagValue
	this.TargetType = targetType
	this.TargetId = targetId
	return &this
}

// NewRoutingRuleWithDefaults instantiates a new RoutingRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutingRuleWithDefaults() *RoutingRule {
	this := RoutingRule{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RoutingRule) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingRule) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RoutingRule) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RoutingRule) SetId(v string) {
	o.Id = &v
}

// GetTagName returns the TagName field value
func (o *RoutingRule) GetTagName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TagName
}

// GetTagNameOk returns a tuple with the TagName field value
// and a boolean to check if the value has been set.
func (o *RoutingRule) GetTagNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TagName, true
}

// SetTagName sets field value
func (o *RoutingRule) SetTagName(v string) {
	o.TagName = v
}

// GetTagValue returns the TagValue field value
func (o *RoutingRule) GetTagValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TagValue
}

// GetTagValueOk returns a tuple with the TagValue field value
// and a boolean to check if the value has been set.
func (o *RoutingRule) GetTagValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TagValue, true
}

// SetTagValue sets field value
func (o *RoutingRule) SetTagValue(v string) {
	o.TagValue = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RoutingRule) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingRule) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RoutingRule) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RoutingRule) SetDescription(v string) {
	o.Description = &v
}

// GetTargetType returns the TargetType field value
func (o *RoutingRule) GetTargetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetType
}

// GetTargetTypeOk returns a tuple with the TargetType field value
// and a boolean to check if the value has been set.
func (o *RoutingRule) GetTargetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetType, true
}

// SetTargetType sets field value
func (o *RoutingRule) SetTargetType(v string) {
	o.TargetType = v
}

// GetTargetId returns the TargetId field value
func (o *RoutingRule) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value
// and a boolean to check if the value has been set.
func (o *RoutingRule) GetTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetId, true
}

// SetTargetId sets field value
func (o *RoutingRule) SetTargetId(v string) {
	o.TargetId = v
}

// GetTargetEmail returns the TargetEmail field value if set, zero value otherwise.
func (o *RoutingRule) GetTargetEmail() string {
	if o == nil || IsNil(o.TargetEmail) {
		var ret string
		return ret
	}
	return *o.TargetEmail
}

// GetTargetEmailOk returns a tuple with the TargetEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingRule) GetTargetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.TargetEmail) {
		return nil, false
	}
	return o.TargetEmail, true
}

// HasTargetEmail returns a boolean if a field has been set.
func (o *RoutingRule) HasTargetEmail() bool {
	if o != nil && !IsNil(o.TargetEmail) {
		return true
	}

	return false
}

// SetTargetEmail gets a reference to the given string and assigns it to the TargetEmail field.
func (o *RoutingRule) SetTargetEmail(v string) {
	o.TargetEmail = &v
}

// GetTargetName returns the TargetName field value if set, zero value otherwise.
func (o *RoutingRule) GetTargetName() string {
	if o == nil || IsNil(o.TargetName) {
		var ret string
		return ret
	}
	return *o.TargetName
}

// GetTargetNameOk returns a tuple with the TargetName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingRule) GetTargetNameOk() (*string, bool) {
	if o == nil || IsNil(o.TargetName) {
		return nil, false
	}
	return o.TargetName, true
}

// HasTargetName returns a boolean if a field has been set.
func (o *RoutingRule) HasTargetName() bool {
	if o != nil && !IsNil(o.TargetName) {
		return true
	}

	return false
}

// SetTargetName gets a reference to the given string and assigns it to the TargetName field.
func (o *RoutingRule) SetTargetName(v string) {
	o.TargetName = &v
}

func (o RoutingRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoutingRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["tagName"] = o.TagName
	toSerialize["tagValue"] = o.TagValue
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["targetType"] = o.TargetType
	toSerialize["targetId"] = o.TargetId
	if !IsNil(o.TargetEmail) {
		toSerialize["targetEmail"] = o.TargetEmail
	}
	if !IsNil(o.TargetName) {
		toSerialize["targetName"] = o.TargetName
	}
	return toSerialize, nil
}

func (o *RoutingRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tagName",
		"tagValue",
		"targetType",
		"targetId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoutingRule := _RoutingRule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoutingRule)

	if err != nil {
		return err
	}

	*o = RoutingRule(varRoutingRule)

	return err
}

type NullableRoutingRule struct {
	value *RoutingRule
	isSet bool
}

func (v NullableRoutingRule) Get() *RoutingRule {
	return v.value
}

func (v *NullableRoutingRule) Set(val *RoutingRule) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutingRule) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutingRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutingRule(val *RoutingRule) *NullableRoutingRule {
	return &NullableRoutingRule{value: val, isSet: true}
}

func (v NullableRoutingRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutingRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


