/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the AuthorizeReplyOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizeReplyOneOf{}

// AuthorizeReplyOneOf Transaction response
type AuthorizeReplyOneOf struct {
	// Transaction ID for the transaction that's been sent to a user
	TxID *string `json:"txID,omitempty"`
}

// NewAuthorizeReplyOneOf instantiates a new AuthorizeReplyOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizeReplyOneOf() *AuthorizeReplyOneOf {
	this := AuthorizeReplyOneOf{}
	return &this
}

// NewAuthorizeReplyOneOfWithDefaults instantiates a new AuthorizeReplyOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizeReplyOneOfWithDefaults() *AuthorizeReplyOneOf {
	this := AuthorizeReplyOneOf{}
	return &this
}

// GetTxID returns the TxID field value if set, zero value otherwise.
func (o *AuthorizeReplyOneOf) GetTxID() string {
	if o == nil || IsNil(o.TxID) {
		var ret string
		return ret
	}
	return *o.TxID
}

// GetTxIDOk returns a tuple with the TxID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizeReplyOneOf) GetTxIDOk() (*string, bool) {
	if o == nil || IsNil(o.TxID) {
		return nil, false
	}
	return o.TxID, true
}

// HasTxID returns a boolean if a field has been set.
func (o *AuthorizeReplyOneOf) HasTxID() bool {
	if o != nil && !IsNil(o.TxID) {
		return true
	}

	return false
}

// SetTxID gets a reference to the given string and assigns it to the TxID field.
func (o *AuthorizeReplyOneOf) SetTxID(v string) {
	o.TxID = &v
}

func (o AuthorizeReplyOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizeReplyOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TxID) {
		toSerialize["txID"] = o.TxID
	}
	return toSerialize, nil
}

type NullableAuthorizeReplyOneOf struct {
	value *AuthorizeReplyOneOf
	isSet bool
}

func (v NullableAuthorizeReplyOneOf) Get() *AuthorizeReplyOneOf {
	return v.value
}

func (v *NullableAuthorizeReplyOneOf) Set(val *AuthorizeReplyOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizeReplyOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizeReplyOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizeReplyOneOf(val *AuthorizeReplyOneOf) *NullableAuthorizeReplyOneOf {
	return &NullableAuthorizeReplyOneOf{value: val, isSet: true}
}

func (v NullableAuthorizeReplyOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizeReplyOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


