/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PermissionGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionGroup{}

// PermissionGroup struct for PermissionGroup
type PermissionGroup struct {
	// Permission group identifier
	Id *string `json:"id,omitempty"`
	// Permission group name
	Name string `json:"name"`
	// Permissions in this group
	Permissions []string `json:"permissions,omitempty"`
}

type _PermissionGroup PermissionGroup

// NewPermissionGroup instantiates a new PermissionGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionGroup(name string) *PermissionGroup {
	this := PermissionGroup{}
	this.Name = name
	return &this
}

// NewPermissionGroupWithDefaults instantiates a new PermissionGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionGroupWithDefaults() *PermissionGroup {
	this := PermissionGroup{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PermissionGroup) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionGroup) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PermissionGroup) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PermissionGroup) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *PermissionGroup) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PermissionGroup) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PermissionGroup) SetName(v string) {
	o.Name = v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *PermissionGroup) GetPermissions() []string {
	if o == nil || IsNil(o.Permissions) {
		var ret []string
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionGroup) GetPermissionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *PermissionGroup) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *PermissionGroup) SetPermissions(v []string) {
	o.Permissions = v
}

func (o PermissionGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

func (o *PermissionGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPermissionGroup := _PermissionGroup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPermissionGroup)

	if err != nil {
		return err
	}

	*o = PermissionGroup(varPermissionGroup)

	return err
}

type NullablePermissionGroup struct {
	value *PermissionGroup
	isSet bool
}

func (v NullablePermissionGroup) Get() *PermissionGroup {
	return v.value
}

func (v *NullablePermissionGroup) Set(val *PermissionGroup) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionGroup) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionGroup(val *PermissionGroup) *NullablePermissionGroup {
	return &NullablePermissionGroup{value: val, isSet: true}
}

func (v NullablePermissionGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


