/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookInput{}

// WebhookInput Input schema for creating or updating a webhook
type WebhookInput struct {
	Url string `json:"url"`
	// Optional secret used to sign webhook payloads (HMAC-SHA256). If a secret is already set, omitting this will preserve the existing secret.
	Secret *string `json:"secret,omitempty"`
	// Optional approval group ID to associate with the webhook
	AuthGroupID *string `json:"authGroupID,omitempty"`
	Events WebhookEvents `json:"events"`
}

type _WebhookInput WebhookInput

// NewWebhookInput instantiates a new WebhookInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookInput(url string, events WebhookEvents) *WebhookInput {
	this := WebhookInput{}
	this.Url = url
	this.Events = events
	return &this
}

// NewWebhookInputWithDefaults instantiates a new WebhookInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookInputWithDefaults() *WebhookInput {
	this := WebhookInput{}
	return &this
}

// GetUrl returns the Url field value
func (o *WebhookInput) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookInput) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookInput) SetUrl(v string) {
	o.Url = v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *WebhookInput) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookInput) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *WebhookInput) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *WebhookInput) SetSecret(v string) {
	o.Secret = &v
}

// GetAuthGroupID returns the AuthGroupID field value if set, zero value otherwise.
func (o *WebhookInput) GetAuthGroupID() string {
	if o == nil || IsNil(o.AuthGroupID) {
		var ret string
		return ret
	}
	return *o.AuthGroupID
}

// GetAuthGroupIDOk returns a tuple with the AuthGroupID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookInput) GetAuthGroupIDOk() (*string, bool) {
	if o == nil || IsNil(o.AuthGroupID) {
		return nil, false
	}
	return o.AuthGroupID, true
}

// HasAuthGroupID returns a boolean if a field has been set.
func (o *WebhookInput) HasAuthGroupID() bool {
	if o != nil && !IsNil(o.AuthGroupID) {
		return true
	}

	return false
}

// SetAuthGroupID gets a reference to the given string and assigns it to the AuthGroupID field.
func (o *WebhookInput) SetAuthGroupID(v string) {
	o.AuthGroupID = &v
}

// GetEvents returns the Events field value
func (o *WebhookInput) GetEvents() WebhookEvents {
	if o == nil {
		var ret WebhookEvents
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhookInput) GetEventsOk() (*WebhookEvents, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Events, true
}

// SetEvents sets field value
func (o *WebhookInput) SetEvents(v WebhookEvents) {
	o.Events = v
}

func (o WebhookInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	if !IsNil(o.AuthGroupID) {
		toSerialize["authGroupID"] = o.AuthGroupID
	}
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *WebhookInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookInput := _WebhookInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookInput)

	if err != nil {
		return err
	}

	*o = WebhookInput(varWebhookInput)

	return err
}

type NullableWebhookInput struct {
	value *WebhookInput
	isSet bool
}

func (v NullableWebhookInput) Get() *WebhookInput {
	return v.value
}

func (v *NullableWebhookInput) Set(val *WebhookInput) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookInput) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookInput(val *WebhookInput) *NullableWebhookInput {
	return &NullableWebhookInput{value: val, isSet: true}
}

func (v NullableWebhookInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


