/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthorizeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizeRequest{}

// AuthorizeRequest struct for AuthorizeRequest
type AuthorizeRequest struct {
	Message string `json:"message"`
	Tag map[string]string `json:"tag"`
	Context *string `json:"context,omitempty"`
	// Arbitrary JSON data that gets passed to webhooks
	Payload map[string]interface{} `json:"payload,omitempty"`
}

type _AuthorizeRequest AuthorizeRequest

// NewAuthorizeRequest instantiates a new AuthorizeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizeRequest(message string, tag map[string]string) *AuthorizeRequest {
	this := AuthorizeRequest{}
	this.Message = message
	this.Tag = tag
	return &this
}

// NewAuthorizeRequestWithDefaults instantiates a new AuthorizeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizeRequestWithDefaults() *AuthorizeRequest {
	this := AuthorizeRequest{}
	return &this
}

// GetMessage returns the Message field value
func (o *AuthorizeRequest) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *AuthorizeRequest) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *AuthorizeRequest) SetMessage(v string) {
	o.Message = v
}

// GetTag returns the Tag field value
func (o *AuthorizeRequest) GetTag() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *AuthorizeRequest) GetTagOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Tag, true
}

// SetTag sets field value
func (o *AuthorizeRequest) SetTag(v map[string]string) {
	o.Tag = v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *AuthorizeRequest) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizeRequest) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *AuthorizeRequest) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *AuthorizeRequest) SetContext(v string) {
	o.Context = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *AuthorizeRequest) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizeRequest) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *AuthorizeRequest) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *AuthorizeRequest) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

func (o AuthorizeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["tag"] = o.Tag
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	return toSerialize, nil
}

func (o *AuthorizeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"tag",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorizeRequest := _AuthorizeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthorizeRequest)

	if err != nil {
		return err
	}

	*o = AuthorizeRequest(varAuthorizeRequest)

	return err
}

type NullableAuthorizeRequest struct {
	value *AuthorizeRequest
	isSet bool
}

func (v NullableAuthorizeRequest) Get() *AuthorizeRequest {
	return v.value
}

func (v *NullableAuthorizeRequest) Set(val *AuthorizeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizeRequest(val *AuthorizeRequest) *NullableAuthorizeRequest {
	return &NullableAuthorizeRequest{value: val, isSet: true}
}

func (v NullableAuthorizeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


