/*
SendAuth API

Authentication and identity management API for SendAuth platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sa-sdk-go

import (
	"encoding/json"
)

// checks if the AuthorizeReplyOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizeReplyOneOf1{}

// AuthorizeReplyOneOf1 Approval response
type AuthorizeReplyOneOf1 struct {
	// Approval ID for the approval that's been sent to an approval group
	ApprovalID *string `json:"approvalID,omitempty"`
}

// NewAuthorizeReplyOneOf1 instantiates a new AuthorizeReplyOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizeReplyOneOf1() *AuthorizeReplyOneOf1 {
	this := AuthorizeReplyOneOf1{}
	return &this
}

// NewAuthorizeReplyOneOf1WithDefaults instantiates a new AuthorizeReplyOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizeReplyOneOf1WithDefaults() *AuthorizeReplyOneOf1 {
	this := AuthorizeReplyOneOf1{}
	return &this
}

// GetApprovalID returns the ApprovalID field value if set, zero value otherwise.
func (o *AuthorizeReplyOneOf1) GetApprovalID() string {
	if o == nil || IsNil(o.ApprovalID) {
		var ret string
		return ret
	}
	return *o.ApprovalID
}

// GetApprovalIDOk returns a tuple with the ApprovalID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizeReplyOneOf1) GetApprovalIDOk() (*string, bool) {
	if o == nil || IsNil(o.ApprovalID) {
		return nil, false
	}
	return o.ApprovalID, true
}

// HasApprovalID returns a boolean if a field has been set.
func (o *AuthorizeReplyOneOf1) HasApprovalID() bool {
	if o != nil && !IsNil(o.ApprovalID) {
		return true
	}

	return false
}

// SetApprovalID gets a reference to the given string and assigns it to the ApprovalID field.
func (o *AuthorizeReplyOneOf1) SetApprovalID(v string) {
	o.ApprovalID = &v
}

func (o AuthorizeReplyOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizeReplyOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApprovalID) {
		toSerialize["approvalID"] = o.ApprovalID
	}
	return toSerialize, nil
}

type NullableAuthorizeReplyOneOf1 struct {
	value *AuthorizeReplyOneOf1
	isSet bool
}

func (v NullableAuthorizeReplyOneOf1) Get() *AuthorizeReplyOneOf1 {
	return v.value
}

func (v *NullableAuthorizeReplyOneOf1) Set(val *AuthorizeReplyOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizeReplyOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizeReplyOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizeReplyOneOf1(val *AuthorizeReplyOneOf1) *NullableAuthorizeReplyOneOf1 {
	return &NullableAuthorizeReplyOneOf1{value: val, isSet: true}
}

func (v NullableAuthorizeReplyOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizeReplyOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


